# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
encoding: "utf-8"
exclude: ["README.md"] # files to exclude
title: Blog - Impulso Financiero 
description: > # this means to ignore newlines until next group 
  Entradas del blog
  Y temas interesantes.. .

#remote (githubpage) | prepend: site.baseurl all urls
#baseurl: "/documentacion" #local path
#local | prepend: site.baseurl may broke some calls may need / before  | prepend: site.baseurl
baseurl: /blog 
roxyurl: "https://impulsofinanciero.com"

paginate: 1 # pagination based on number of posts
paginate_path: "page:num"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

#url: "http://localhost:4000" # the base hostname & protocol for your site
links:
  twitter: ImpulsoFin 
  facebook: ImpulsoFinancieroMx 
  github: impulsofinanciero
  www: "https://impulsofinanciero.com"

# Build settings

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

#highlighter: pygments
highlighter: rouge

collections:
  docs:
    output: true
    permalink: /:path

#Copy right Sets
owner: Impulso Financiero

# PLUGINS
plugins: [jekyll-paginate]
